In [2]:
import numpy as np
import pandas as pd

finding missing data

In [3]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [4]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [5]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

removind missing data

In [6]:
df.dropna()  #removes every row which has any missing data

     A  B    C    D
0  1.0  1  1.0  1.0

In [7]:
df.dropna(thresh=3)  #thres is used to keep rows (or columns) that have at least a minimum number of non-null values.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

filling the missing data

In [13]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [12]:
values={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0